name = "textbook"
defaultTargets = ["DemoTextbook", "textbook"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.24.0"

[[lean_lib]]
name = "DemoTextbook"

[[lean_exe]]
name = "textbook"
root = "DemoTextbookMain"
