name = "textbook"
defaultTargets = ["TextbookTemplate", "textbook"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.27.0"

[[lean_lib]]
name = "TextbookTemplate"

[[lean_exe]]
name = "textbook"
root = "TextbookTemplateMain"
